[2024-10-20 18:58:36 UTC] Step train_model has started.

[2024-10-20 18:58:36 UTC] 2024/10/21 00:28:17 INFO mlflow.tracking.fluent: Experiment with name 'data_pipeline' does not exist. Creating a new experiment.

[2024-10-20 18:58:36 UTC] Error in training model: Run with UUID 552e27eb062440c98e87def876e4eb71 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True

[2024-10-20 18:58:38 UTC] /mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/integrations/mlflow/experiment_trackers/mlflow_experiment_tracker.py:255: FutureWarning: ``mlflow.gluon.autolog`` is deprecated since 2.5.0. This method will be removed in a future release.
  module.autolog(disable=True)

[2024-10-20 18:58:38 UTC] Failed to run step train_model after 1 retries. Exiting.

[2024-10-20 18:58:38 UTC] Run with UUID 552e27eb062440c98e87def876e4eb71 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
Traceback (most recent call last):
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 292, in launch
    self._run_step(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 499, in _run_step
    self._run_step_without_step_operator(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.py", line 583, in _run_step_without_step_operator
    runner.run(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/orchestrators/step_runner.py", line 198, in run
    return_values = step_instance.call_entrypoint(
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/zenml/steps/base_step.py", line 692, in call_entrypoint
    return self.entrypoint(**validated_args)
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/steps/model_training.py", line 75, in train_model
    raise e
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/steps/model_training.py", line 36, in train_model
    with mlflow.start_run():
  File "/mnt/c/Users/risha/Desktop/retail-prize-optimization-MLOps/venv/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 321, in start_run
    raise Exception(
Exception: Run with UUID 552e27eb062440c98e87def876e4eb71 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True

